### ISSUE TITLE
rename repository

### ISSUE THREAD

**Issue by professor-enoqueleal** [RogerSouza1/sistema-de-clinica-medica#1]
Por favor fazer o _rename_ do repositório. 

O nome do repositório não precisa conter a palavra **projeto**.

Para o nome de repositório, seguir a convenção onde todas as letras devem ser minúsculas e as palavras separadas com **hífen** no padrão **kebab-case** https://coodesh.com/blog/candidates/dicas/convencoes-de-codificacao-do-camelcase-ao-kebab-case/

**Comment by carladfb** [comment]
Projeto devidamente renomeado seguindo os padrões solicitados. 
Nome: "sistema-de-clinica-medica".
