### ISSUE TITLE
Atualizar o Readme.md

### ISSUE THREAD

**Issue by RogerSouza1** [RogerSouza1/sistema-de-clinica-medica#2]
Atualizar o Readme.md do projeto adicionando as novas funcionalidades abaixo e as imagens do projeto.

# Lista de Funcionalidades

## Requisitos Funcionais

1. O usuário deve conseguir se cadastrar como Paciente ou Médico
2. O usuário deve conseguir consultar e alterar suas informações cadastrais necessárias
3. O usuário deve conseguir fazer login em sua Área Credenciada específica
4. O usuário deve conseguir alterar a sua senha caso queira fornecendo o CPF e Email
5. O paciente deve conseguir agendar suas consultas, selecionando a especialidade, data e horário disponível
6. O paciente deve conseguir acessar suas consultas agendadas e ter a opção de confirmar ou cancelar elas
7. O médico deve conseguir definir e alterar seus horários disponíveis individualmente por data e horário
8. O médico deve ter acesso as consultas confirmadas que ele terá no dia e consultar o respectivo prontuário
9. O médico deve conseguir cancelar suas consultas individualmente caso queira

## Requisitos Não-Funcionais

1. O site deve conter uma página principal que mostre as especialidades atendidas
2. O site deve conter um sobre referente ao plano
3. O site deve conter uma descrição de cada especialidades

## Regras de Negócio

1. O usuário só deve conseguir se cadastrar se ele tiver mais de 18 anos no dia do cadastro
2. A senha do usuário deve conter no mínimo 8 caracteres, sendo uma letra maiúscula e um número
3. O usuário pode somente adicionar no máximo 3 dependentes por CPF
4. No cadastro, a sua finalização só pode ser completa se todos os dados solicitados forem inseridos e validados
5. A consulta deve ser confirmada pelo Paciente até um dia antes do atendimento, caso não ela será automaticamente cancelada

**Comment by Pelifefe** [comment]
Readme realizado

**Comment by RogerSouza1** [comment]
@Pelifefe 

Necessário atualizar o readme.md com as funcionalidade completas, as telas se houve alguma alteração visual e a modelagem do banco de dados, tanto o MER quanto o DER.
